---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Header 1

```{r setup}
#| include: false

source(here::here("R/functions.R"))
```

## Prepare HR data
```{r}
hr_data <- read_all("HR.csv.gz") |>
  get_participant_id() |>
  summarise_by_datetime()

summarise_by_datetime(hr_data)
```

## Prepare IBI data
```{r}
ibi_data <- read_all("IBI.csv.gz") |>
  get_participant_id() |>
  summarise_by_datetime()
```

## Prepare TEMP data
```{r}
temp_data <- read_all("TEMP.csv.gz") |>
  get_participant_id() |>
  summarise_by_datetime()
```

## Prepare BVP data
```{r}
bvp_data <- read_all("BVP.csv.gz") |>
  get_participant_id() |>
  summarise_by_datetime()
```

## Prepare EDA data
```{r}
eda_data <- read_all("EDA.csv.gz") |>
  get_participant_id() |>
  summarise_by_datetime()
```


## Process survey data
```{r}
survey_tidy <- here::here("data-raw/nurses-stress/survey-results.csv.gz") |>
  read() |>
  tidy_survey_dates()

survey_long <- survey_tidy |>
  survey_to_long()
```


## Joining datasets

```{r}
nurses_stress <- survey_long |>
  dplyr::full_join(survey_tidy) |>
  dplyr::full_join(hr_data) |>
  dplyr::full_join(ibi_data) |>
  dplyr::full_join(temp_data) |>
  dplyr::full_join(bvp_data) |>
  dplyr::full_join(eda_data)
```

```{r}
readr::write_csv(nurses_stress, here::here("data/nurses-stress.csv"))
usethis::use_git_ignore("data/nurses-stress.csv")
```
